  michael.conf: 
    [INPUT]
      Name              tail
      Tag               michael.*
      Path              /var/log/containers/*api*.log
      DB                /tmp/flb_michael.db
      Mem_Buf_Limit     50MB
      Skip_Long_Lines   On
      Refresh_Interval  10

    [FILTER]
      Name                kubernetes
      Match               michael.*
      Merge_Log           On
      Keep_Log            Off
      K8S-Logging.Parser  On

   [OUTPUT]
      Name                cloudwatch_logs
      Match               michael.*
      region              af-south-1
      log_group_name      /eks/michael-logs/pods
      log_stream_prefix   michael-pod-
      auto_create_group   true

