apiVersion: cloudwatch.aws.amazon.com/v1alpha1
kind: AmazonCloudWatchAgent
metadata:
  creationTimestamp: "2025-02-17T13:59:10Z"
  generation: 5
  labels:
    app.kubernetes.io/managed-by: amazon-cloudwatch-agent-operator
  name: cloudwatch-agent
  namespace: amazon-cloudwatch
  resourceVersion: "84464778"
  uid: a1bec93e-e867-4e83-ad22-13cd5d5f2e56
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: eks.amazonaws.com/compute-type
            operator: NotIn
            values:
            - fargate
  config: |
    {
      "agent": {
        "region": "af-south-1"
      },
      "logs": {
        "metrics_collected": {
          "application_signals": {
            "hosted_in": "nonprod_pfp_eks_cluster"
          },
          "kubernetes": {
            "cluster_name": "nonprod_pfp_eks_cluster",
            "enhanced_container_insights": true
          }
        },
        "logs_collected": {
          "files": {
            "collect_list": [
              {
                "file_path": "/var/log/containers/*.log",
                "log_group_name": "/aws/eks/pod/api",
                "log_stream_name": "{hostname}",
                "multi_line_start_pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}",
                "timezone": "UTC"
              }
            ]
          }
        }
      },
      "traces": {
        "traces_collected": {
          "application_signals": {}
        }
      }
    }
  env:
  - name: K8S_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: HOST_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: K8S_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  hostNetwork: true
  image: 877085696533.dkr.ecr.af-south-1.amazonaws.com/eks/observability/cloudwatch-agent:1.300052.0b1024
  ingress:
    route: {}
  managementState: managed
  mode: daemonset
  nodeSelector:
    kubernetes.io/os: linux
  observability:
    metrics: {}
  podDisruptionBudget:
    maxUnavailable: 1
  priorityClassName: system-node-critical
  prometheus: {}
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 128Mi
  serviceAccount: cloudwatch-agent
  targetAllocator:
    prometheusCR:
      scrapeInterval: 30s
    resources: {}
  tolerations:
  - operator: Exists
  updateStrategy: {}
  upgradeStrategy: automatic
  volumeMounts:
  - mountPath: /rootfs
    name: rootfs
    readOnly: true
  - mountPath: /var/run/docker.sock
    name: dockersock
    readOnly: true
  - mountPath: /run/containerd/containerd.sock
    name: containerdsock
  - mountPath: /var/lib/docker
    name: varlibdocker
    readOnly: true
  - mountPath: /sys
    name: sys
    readOnly: true
  - mountPath: /dev/disk
    name: devdisk
    readOnly: true
  - mountPath: /etc/amazon-cloudwatch-observability-agent-cert
    name: agenttls
    readOnly: true
  - mountPath: /etc/amazon-cloudwatch-observability-agent-client-cert
    name: agentclienttls
    readOnly: true
  - mountPath: /etc/amazon-cloudwatch-observability-agent-server-cert
    name: agentservertls
    readOnly: true
  - mountPath: /var/lib/kubelet/pod-resources
    name: kubelet-podresources
  volumes:
  - hostPath:
      path: /var/lib/kubelet/pod-resources
      type: Directory
    name: kubelet-podresources
  - hostPath:
      path: /
    name: rootfs
  - hostPath:
      path: /var/run/docker.sock
    name: dockersock
  - hostPath:
      path: /var/lib/docker
    name: varlibdocker
  - hostPath:
      path: /run/containerd/containerd.sock
    name: containerdsock
  - hostPath:
      path: /sys
    name: sys
  - hostPath:
      path: /dev/disk/
    name: devdisk
  - name: agenttls
    secret:
      items:
      - key: ca.crt
        path: tls-ca.crt
      secretName: amazon-cloudwatch-observability-agent-cert
  - name: agentclienttls
    secret:
      items:
      - key: ca.crt
        path: tls-ca.crt
      secretName: amazon-cloudwatch-observability-agent-client-cert
  - name: agentservertls
    secret:
      items:
      - key: tls.crt
        path: server.crt
      - key: tls.key
        path: server.key
      secretName: amazon-cloudwatch-observability-agent-server-cert
status:
  version: 0.0.0
