apiVersion: v1
data:
  enable-network-policy-controller: "false"
  enable-windows-ipam: "false"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"enable-network-policy-controller":"false","enable-windows-ipam":"false"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"aws-vpc-cni","app.kubernetes.io/name":"aws-node","app.kubernetes.io/version":"v1.14.1","k8s-app":"aws-node"},"name":"amazon-vpc-cni","namespace":"kube-system"}}
  creationTimestamp: "2023-10-07T14:42:59Z"
  labels:
    app.kubernetes.io/instance: aws-vpc-cni
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-node
    app.kubernetes.io/version: v1.19.2
    helm.sh/chart: aws-vpc-cni-1.19.2
    k8s-app: aws-node
  name: amazon-vpc-cni
  namespace: kube-system
  resourceVersion: "267"
  uid: 292c9ce1-39c5-4dde-b1a4-b849d3d990e0
