apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::277707115427:role/preprod_bm_eks_nodegroup_role
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - eks-console-dashboard-restricted-access-group
      - view
      rolearn: arn:aws:iam::277707115427:role/BeyondMobilePPRD-ProdAdmin-NonProd-Ltd
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
