apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
      annotations:
        version: "1.0.0-718"
    spec:
      containers:
        - name: client
          image: 835860129811.dkr.ecr.af-south-1.amazonaws.com/dev-dde:client
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BASE_URL
              value: "/api"
---
apiVersion: v1
kind: Service
metadata:
  name: client-serv
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
