apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
      annotations:
        version: "1.0.0-565"
    spec:
      containers:
        - name: worker
          image: 835860129811.dkr.ecr.af-south-1.amazonaws.com/dev-dde:worker
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: uat
            - name: SERVICE_NAME
              value: worker-service
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: host
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: host
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: port
            - name: MAIL_USER
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: user
            - name: MAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: pass
            - name: MAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: from
            - name: ANOMALY_EMAIL_RECIPIENTS
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: anomaly_email_recipients
            #AWS S3
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: accessKeyId
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: secretAccessKey
            - name: REGION
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: region
            - name: BUCKET
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: bucket
            - name: FOLDER_SME
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: folderSme
            - name: FOLDER_UNL
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: folderUnl
            - name: FOLDER_DUMP
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: folderDump
            #NATS
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: dde_app
            - name: REDIS_HOST
              value: worker-redis-srv
