apiVersion: apps/v1
kind: Deployment
metadata:
  name: dde-depl
  labels:
    app: dde
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dde
  template:
    metadata:
      labels:
        app: dde
    spec:
      #restartPolicy: Never
      containers:
        - name: dde
          image: 195116001166.dkr.ecr.af-south-1.amazonaws.com/dde-ecr:dde
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_NAME
              value: dde-service
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: host
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: dde_app

---
apiVersion: v1
kind: Service
metadata:
  name: dde-serv
spec:
  selector:
    app: dde
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
