apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"aws-vpc-cni","app.kubernetes.io/name":"aws-node","app.kubernetes.io/version":"v1.11.4","k8s-app":"aws-node"},"name":"eniconfigs.crd.k8s.amazonaws.com"},"spec":{"group":"crd.k8s.amazonaws.com","names":{"kind":"ENIConfig","plural":"eniconfigs","singular":"eniconfig"},"preserveUnknownFields":false,"scope":"Cluster","versions":[{"name":"v1alpha1","schema":{"openAPIV3Schema":{"type":"object","x-kubernetes-preserve-unknown-fields":true}},"served":true,"storage":true}]}}
  creationTimestamp: "2023-01-18T06:32:42Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: aws-vpc-cni
    app.kubernetes.io/name: aws-node
    app.kubernetes.io/version: v1.11.4
    k8s-app: aws-node
  name: eniconfigs.crd.k8s.amazonaws.com
  resourceVersion: "248"
  uid: 0049e45c-5166-4fc9-ae87-aa40f6bb5fbb
spec:
  conversion:
    strategy: None
  group: crd.k8s.amazonaws.com
  names:
    kind: ENIConfig
    listKind: ENIConfigList
    plural: eniconfigs
    singular: eniconfig
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
status:
  acceptedNames:
    kind: ENIConfig
    listKind: ENIConfigList
    plural: eniconfigs
    singular: eniconfig
  conditions:
  - lastTransitionTime: "2023-01-18T06:32:42Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2023-01-18T06:32:42Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
