apiVersion: apps/v1
kind: Deployment
metadata:
  name: loader-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loader
  template:
    metadata:
      labels:
        app: loader
    spec:
      containers:
        - name: loader
          image: 195116001166.dkr.ecr.af-south-1.amazonaws.com/dde-ecr:loader
          imagePullPolicy: Always
          env:
            - name: SERVICE_NAME
              value: loader-service
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_ENV
              value: local
            - name: LOG_LEVEL
              value: debug
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: host
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: host
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: port
            - name: MAIL_USER
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: user
            - name: MAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: pass
            - name: MAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: from
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: dde_app
            - name: REDIS_HOST
              value: loader-redis-srv
